##Example exec. ansible-playbook vcenters.yml -i inventory.ini --ask-vault-pass

---
- name: Update VCenter Server DVS Shaping
  hosts: vcenters
  gather_facts: no

  tasks:

    - name: Modify DVS PG shaping
      community.vmware.vmware_dvs_portgroup:
        validate_certs: no
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        portgroup_name: "{{ port_group }}"
        switch_name: "{{ dvs_name }}"
        state: present
        port_binding: static
        vlan_id: "{{ vlan }}"
        in_traffic_shaping:
          inherited: false
          enabled: true
          average_bandwidth: "{{bandwidth}}"
          peak_bandwidth: "{{bandwidth}}"
          burst_size: "{{burst}}"
        out_traffic_shaping:
          inherited: false
          enabled: true
          average_bandwidth: "{{bandwidth}}"
          peak_bandwidth: "{{bandwidth}}"
          burst_size: "{{burst}}"
      delegate_to: localhost